### PR TITLE
Feat: Add groups for LSP semantic tokens

### PR DESCRIPTION
**Pull request by mactep**
I'm not sure what I am doing here, but my Lua code was getting white, so I linked some highlight groups to Treesitter ones.

### CODE REVIEW

**Comment by mactep** [comment]
It'll probably be better to change the notation to `['@lsp.type.<group>'] = { ... }`

**Comment by mactep** [comment]
TODO: use the other syntax and add all these tokens https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens

**Comment by AlexvZyl** [comment]
Thanks for the PR!  

What do you mean it was "getting white"?  Was everything completely white, or just some highlights white?

**Comment by AlexvZyl** [comment]
It seems like these tokens are new, [tokyonight added them recently](https://github.com/folke/tokyonight.nvim/blob/1b0c88094548a62641ece1e668fa9a234e1c539e/lua/tokyonight/theme.lua#L256-L272).

**Comment by AlexvZyl** [comment]
[This PR](https://github.com/neovim/neovim/pull/22022) seems to be the culprit.

**Comment by AlexvZyl** [comment]
It would have been really nice if all of the Neovim colorschemes were just forks of some core repository, and then just override colors as the developers see fit...

**Comment by AlexvZyl** [comment]
I am going to leave this open until there is a confirmation (from either you or me) that this groups are correct.  I suspect they are, I just don't have the time now to double-check.

**Comment by mactep** [comment]
> [This PR](https://github.com/neovim/neovim/pull/22022) seems to be the culprit.

According to the docs we can simply disable all tokens, but I thought it would be useful to have easy access to this variables. Just in case anyone needs it:

```lua
for _, group in ipairs(vim.fn.getcompletion("@lsp", "highlight")) do
  vim.api.nvim_set_hl(0, group, {})
end
```

> I am going to leave this open until there is a confirmation (from either you or me) that these groups are correct. I suspect they are, I just don't have the time now to double-check.

Following that script provided by neovim team, the following seems to be "official" groups, but I guess things may change until a stable release:

- @lsp.type.class
- @lsp.type.decorator
- @lsp.type.enum
- @lsp.type.enumMember
- @lsp.type.function
- @lsp.type.interface
- @lsp.type.macro
- @lsp.type.method
- @lsp.type.namespace
- @lsp.type.parameter
- @lsp.type.property
- @lsp.type.struct
- @lsp.type.type
- @lsp.type.typeParameter
- @lsp.type.variable

The docs also say that many groups are linked by default to other highlight groups:

- @lsp.type.class         Structure
- @lsp.type.decorator     Function
- @lsp.type.enum          Structure
- @lsp.type.enumMember    Constant
- @lsp.type.function      Function
- @lsp.type.interface     Structure
- @lsp.type.macro         Macro
- @lsp.type.method        Function
- @lsp.type.namespace     Structure
- @lsp.type.parameter     Identifier
- @lsp.type.property      Identifier
- @lsp.type.struct        Structure
- @lsp.type.type          Type
- @lsp.type.typeParameter TypeDef
- @lsp.type.variable      Identifier

I think we can drop the other notation from this PR, keep folke's changes and add the other possible tokens commented out as an "easy access" for future improvements. What do you think @AlexvZyl?

**Comment by AlexvZyl** [comment]
Yes, I agree with you.  You mind doing that?

**Comment by mactep** [comment]
Sure, I'll get this done later today or tomorrow.

**Comment by AlexvZyl** [comment]
Beautiful, thanks for the work!

**Comment by lostl1ght** [comment]
There is a much easier way to disable semantic tokens:

**Comment by AlexvZyl** [comment]
> I've read somewhere that it is a 'chosen' way to do that instead of messing with highlight groups.

If you can find this source you are more than welcome to open a PR.  We are currently not doing that since we are basically doing what Folke is doing over at tokyonight.

**Pull request merged**
