### PR TITLE
Transparency support & fix testing in a PR

### PR DESCRIPTION
**Pull request by lcrownover**
### Added `override` table

This table can be used to override color and styling of any element.

### Redesigned the `syntax` config to operate more like the original Nord theme

The functionality of the `syntax` table was maintained, but now with the `override` table, you can enable/disable bold/italic on particular items, if the general `bold` or `italic` booleans don't do what you want.

### Added `transparency` config option

This option sets a few key element backgrounds to `c.none` for a cohesive transparent style. You can always use the `override` table to enable/disable transparency in a more surgical manner.

### CODE REVIEW

**Comment by lcrownover** [comment]
Fixed merge conflict with the README.

**Comment by AlexvZyl** [comment]
Ah, awesome!  I was planning on doing this, thanks!

Will test it a bit later.

Also, I see my CI is not working correctly.  Gonna try and fix that.

**Comment by AlexvZyl** [comment]
That's wrong.  Just trying to figure out how to get `Icrownover/nordic.nvim`.

**Comment by AlexvZyl** [comment]
Cool, working beautifully now.  A bit messy, I will clean it up a bit later.

**Comment by AlexvZyl** [comment]
Almost ready to merge.

**Pull request merged**
