### PR TITLE
feat(highlights): added highlights to @markup tags

### PR DESCRIPTION
**Pull request by juniorsundar**
Covers the highlights for `@markup` tags which means colour highlights are now back in Markdown as well as Neorg.

I used tokyonight.nvim to get the tags that need highlighting, and used the existing flavours (colour allocation) to assign the highlight colours to remain true to the creator's intention with this theme.

### CODE REVIEW

**Comment by AlexvZyl** [comment]
Awesome, thanks!

Will come back to this after #113.

**Comment by AlexvZyl** [comment]
@juniorsundar Are you able to resolve the merge conflicts?  Might be a bit rough.

**Comment by juniorsundar** [comment]
Oh wow! That's a huge refactor!
I think it will be easier to just implement the feature additions into the current state of `main` than to spend time resolving these merge conflicts.
Unless you are already planning to address the highlight groups I've added, you can close this PR and I'll just open a new one by pulling from `main` and adding the highlight groups to that.

**Comment by AlexvZyl** [comment]
You can open a new PR if you want?  Otherwise I will do it.

**Comment by AlexvZyl** [comment]
You can open a new PR if you want?  Otherwise I will do it.

**Comment by juniorsundar** [comment]
I'll leave that decision up to you.
I have very little confidence in my ability to resolve merge conflicts with git without accidentally causing the world to revert to a prehistoric commit.

**Comment by AlexvZyl** [comment]
Ok let's close this one then you make a new PR.  I want you to have the contribution.

**Pull request closed without merging**
