### PR TITLE
Lazy.nvim installation doc, iterm2 & windows-terminal

### PR DESCRIPTION
**Pull request by lcrownover**

### CODE REVIEW

**Comment by AlexvZyl** [comment]
Thanks for the PR!

cc: @Lunchb0ne, #18.

**Comment by Lunchb0ne** [comment]
Haha that's great to see, I was thinking of doing this over the weekend

**Comment by lcrownover** [comment]
Thanks. It's a great looking theme, I always like Nord but it was too bright and too stale. This one caught my eye as a perfect balance of slightly darker and more colorful.

The iterm2 theme was created by manually copying colors. I wonder how much would go into automatically generating themes based on the palette. I know [tokyonight](https://github.com/folke/tokyonight.nvim) does this, but folke is a magician 😋 

Next up, transparency support.

**Comment by lcrownover** [comment]
Also popped a windows-terminal theme in there since I gotta have all my environments match :)

**Comment by AlexvZyl** [comment]
Also, could we rename `contrib` -> `extras`?

**Pull request merged**
