### PR TITLE
added chroma support via platforms/chroma/nordic.xml

### PR DESCRIPTION
**Pull request by avih7531**
Added support for [alecthomas'](https://github.com/alecthomas) [chroma](https://github.com/alecthomas/chroma) syntax highlighter

### CODE REVIEW

**Comment by 5-pebbles** [comment]
can you share some screenshots? The code looks good though.

**Comment by avih7531** [comment]
Will do when I get back to my pc. Thanks!

**Comment by 5-pebbles** [comment]
@avih7531 I figure I should just remind you this **PR** is still open. I am waiting on those screenshots before I request a review from Alex, but he is on vacation, so there is no rush.

**Comment by avih7531** [comment]
Hi pebbles,

Sorry for the long wait! I abandoned chroma as I decided that it A. didn't look good and B. wasn't useful software.

I've since refactored the project I had that used chroma, so I can't provide any screenshots, but it _~worked_

All the best

**Pull request closed without merging**
