### PR TITLE
Refactor Fix State and Config Reloading

### PR DESCRIPTION
**Pull request by 5-pebbles**
## Changes

* feat(cursorline)!: add cursorline bg option for visual selection color

- Add cursorline.bg option with default value of "#191D24".
- Remove cursorline.theme option.
- Update docs to reflect new defaults.

BREAKING CHANGE: cursorline.theme option removed, replaced by cursorline.bg.

* fix(extend_palette): fix cursorline_bg set to none when transparent_bg is true.

& fix error message colors/init.lua:64: attempt to index global 'O' (a nil value).

* fix: reduce_blue updates on extend palette

* refactor: cleaned up first run of extend palette

* fix: swap_backgrounds is no longer just a toggle.

* feat(config): allow use of base palette in default config.

### Breaking Changes

- The `cursorline.theme` option has been removed and replaced with `cursorline.bg`.

### CODE REVIEW

**Comment by AlexvZyl** [comment]
Ah, yes I did not think of people wanting to reload the config.  Your way of doing it in this PR is nicer.

Though, we should keep the work in #113, since that takes care of the scenario where someone loads the colors before they setup the plugin.

I think what we should do is add you as a contributor so that you can branch off of #113 and add some of these changes you suggest here.  I will set that up after work today.

**Comment by 5-pebbles** [comment]
I think it would be easier to extend this with the changes from #113.

Mainly because I think `apply_modifications` is a bad I idea.

You would still need to call `extend_palette` to apply `transparent_bg`, `bg_highlight`, and `bright_border`.

6b417a4 can be merged into this without issues, and I can fairly easily add the other changes from 78624e4.

but I am fine with doing it the other way as well. Thanks

**Comment by 5-pebbles** [comment]
> 6b417a4 can be merged into this without issues

Wait, no it can't, never mind its easier to build on #113

**Comment by AlexvZyl** [comment]
> I think it would be easier to extend this with the changes from #113.
> 
> Mainly because I think `apply_modifications` is a bad I idea.


Not necessarily, you just have to take into account that it should be able to go both ways.  Anyway, we can implement it like you do in this PR.

**Comment by AlexvZyl** [comment]
@5-pebbles Added you as collaborator!  Make a branch from #113 and open a PR into it :)

**Pull request closed without merging**
