### PR TITLE
Support mini.statusline

### PR DESCRIPTION
**Pull request by leaysgur**
Hello! 👋🏻   I'd like to support `mini.statusline`.

- Colors are based on current `lualine` integration
  - https://github.com/AlexvZyl/nordic.nvim/blob/main/lua/lualine/themes/nordic.lua
- Highlight groups for `mini.statusline`
  - https://github.com/echasnovski/mini.statusline/blob/main/lua/mini/statusline.lua#L44-L63

(This is my first time contributing to a Lua project, so please let me know if I missed something. 😅 )

### CODE REVIEW

**Comment by AlexvZyl** [comment]
Thanks for the PR!  Now that you mention it being based on lualune... What if you did something like:

```lua
local C = require 'lualine.themes.nordic'

return {
    MiniStatuslineModeNormal = {
        bg = C.normal.a.bg,
        fg = C.normal.a.fg,
        bold = true,
    },
    -- ...
}
```

And then use those colors to setup mini.statusline?  Then colors will change with lualine changes.

**Comment by leader22** [comment]
Thank you for the review!

I thought about it too at first, but didn't because `nightfox` and `tokyonight` seemed to keep them separate.
I'm not sure but there may be some cases where `lualine` should not be the base spec?

Which do you prefer? 👀

**Comment by AlexvZyl** [comment]
'lualine.themes' is cloned when 'nordic' is cloned... I can't imagine a situation where it will not be in the base spec?  Or am I missing somthing?

**Comment by leader22** [comment]
Oh, sorry!

- `lualine` seems to consist of 3 units(a, b, c)
- If someday another statusline module is introduced and it consists of 4 units, 4th one should be defined independently
- It might feel inconsistent?

And now I come up with another concern.

- If one day `lualine` gets major updates and changes its data structure
- All other statusline modules that depend on `lualine` spec may be need to updated too
- Is it OK?

This was my intention. 😄

**Comment by AlexvZyl** [comment]
I am unable to keep every single plugin up to date.  I would much rather have mini.statusline break due a change in lualine, than have to go to a bunch of plugins when I want to change one color.

I plan on making neo-tree depend on nvim-tree in the same way.

**Comment by AlexvZyl** [comment]
> Thanks for the PR!
> 
> Now that you mention it being based on lualune... What if you did something like:
> 
> ```lua
> local C = require 'lualine.themes.nordic'
> 
> return {
>     MiniStatuslineModeNormal = {
>         bg = C.normal.a.bg,
>         fg = C.normal.a.fg,
>         bold = (C.normal.a.gui == 'bold'),
>     },
>     -- ...
> }
> ```
> 
> And then mini.statusline will always be up to date with lualine.

So if you don't mind doing it like this?  I much prefer this way, after thinking about it :)

**Comment by leaysgur** [comment]
That's all right. (Just wanted to make sure 👍🏼)

I'll try to fix it tonight.

**Comment by leaysgur** [comment]
@AlexvZyl Fixed~~!

**Comment by AlexvZyl** [comment]
Do you mind adding a screenshot?

**Comment by leaysgur** [comment]
Sure! like this?

### Before

Screen Shot 2023-08-05 at 22 36 07
Screen Shot 2023-08-05 at 22 36 18
Screen Shot 2023-08-05 at 22 38 55
Screen Shot 2023-08-05 at 22 36 54
Screen Shot 2023-08-05 at 22 36 44

### After

Screen Shot 2023-08-05 at 22 37 24
Screen Shot 2023-08-05 at 22 37 32
Screen Shot 2023-08-05 at 22 37 47
Screen Shot 2023-08-05 at 22 37 55
Screen Shot 2023-08-05 at 22 38 06

Please let me know what you would like to record if you have any requests. 📸

**Comment by AlexvZyl** [comment]
Thanks for bearing with my pedantry :)

**Pull request merged**
