### PR TITLE
feat(platforms): add support for fish shell

### PR DESCRIPTION
**Pull request by XXiaoA**
Screenshot_2023-07-12-16-00-43

### CODE REVIEW

**Comment by XXiaoA** [comment]
@AlexvZyl  Thx for ur advice. I tried `gray3` for autosuggesting, but it is too dim, i think.
图片

Maybe `gray5` is more suitable ?
图片

**Comment by XXiaoA** [comment]
Ummm orange looks like red which refer to error of param. Yellow is easier to tell between error and normal,  i think.
图片
图片

**Comment by AlexvZyl** [comment]
I did not forget about this PR.  Would you mind showing me a screenshot of what the final product looks like?  Sorry for leaving you hanging.

**Comment by XXiaoA** [comment]
Here.
图片

Anything else should be adjusted?

**Comment by AlexvZyl** [comment]
This color seems off.
image
Can you make that the normal orange?

**Comment by XXiaoA** [comment]
> This color seems off. image Can you make that the normal orange?

This git status are showed by `starship`, which is not related to fish. 🤣
https://github.com/XXiaoA/dotfiles/blob/f514270e01ad590cdbfb5fdac347f9fe64144101/starship/starship.toml#L13

**Comment by AlexvZyl** [comment]
Did you set the terminal colors?  Because both fish and starship should be using the terminal colors.

**Comment by XXiaoA** [comment]
I don't remember I set the terminal colors manually.

**Comment by AlexvZyl** [comment]
Hmm... Becase now that I think of it, you actually want to set the terminal colors and not each component running in the terminal.  What terminal are you using?

**Comment by XXiaoA** [comment]
Wezterm. And I have used nordic's wezterm theme

**Comment by AlexvZyl** [comment]
There might be some colors missing in the wezterm theme I think.

**Comment by XXiaoA** [comment]
Okay. Anyway, thanks for merging

**Pull request merged**
